AllCops:
  TargetRubyVersion: 3.4.1
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false
